<a href="https://colab.research.google.com/github/Pranayshukla0610/Data-Science-Projects/blob/main/Notebook_1_Customers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install faker --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 16.7 MB/s eta 0:00:00

In [2]:
import random
import pandas as pd
import numpy as np

from faker import Faker
from datetime import datetime

In [3]:
fake = Faker("en_IN")

In [4]:
random.seed(42)
np.random.seed(42)
Faker.seed(42)

In [5]:
NUMBER_OF_CUSTOMERS = 15000

In [6]:
segments = [
    'Consumer',
    'Corporate',
    'Home Office'
]

In [7]:
segment_probability = [
    0.60,
    0.25,
    0.15
]

In [8]:
genders = [
    'Male',
    'Female'
]

In [9]:
gender_probability = [
    0.50,
    0.50
]

In [10]:
city_state = {

    "Lucknow":"Uttar Pradesh",
    "Kanpur":"Uttar Pradesh",
    "Varanasi":"Uttar Pradesh",
    "Agra":"Uttar Pradesh",
    "Noida":"Uttar Pradesh",

    "Delhi":"Delhi",

    "Mumbai":"Maharashtra",
    "Pune":"Maharashtra",
    "Nagpur":"Maharashtra",
    "Nashik":"Maharashtra",

    "Bengaluru":"Karnataka",
    "Mysuru":"Karnataka",
    "Hubli":"Karnataka",

    "Hyderabad":"Telangana",
    "Warangal":"Telangana",

    "Chennai":"Tamil Nadu",
    "Coimbatore":"Tamil Nadu",
    "Madurai":"Tamil Nadu",

    "Jaipur":"Rajasthan",
    "Jodhpur":"Rajasthan",

    "Ahmedabad":"Gujarat",
    "Surat":"Gujarat",
    "Vadodara":"Gujarat",

    "Bhopal":"Madhya Pradesh",
    "Indore":"Madhya Pradesh",

    "Patna":"Bihar",
    "Gaya":"Bihar",

    "Kolkata":"West Bengal",
    "Siliguri":"West Bengal",

    "Bhubaneswar":"Odisha",
    "Cuttack":"Odisha",

    "Chandigarh":"Punjab",

    "Amritsar":"Punjab",

    "Kochi":"Kerala",
    "Thiruvananthapuram":"Kerala",

    "Guwahati":"Assam",

    "Ranchi":"Jharkhand",

    "Raipur":"Chhattisgarh",

    "Dehradun":"Uttarakhand",

    "Shimla":"Himachal Pradesh"
}

In [11]:
cities = list(city_state.keys())

In [12]:
MIN_AGE = 18
MAX_AGE = 70

In [13]:
print("Total Customers :", NUMBER_OF_CUSTOMERS)

print("Cities :", len(cities))

print("Segments :", segments)

print("Gender :", genders)

print("Minimum Age :", MIN_AGE)

print("Maximum Age :", MAX_AGE)

Total Customers : 15000
Cities : 40
Segments : ['Consumer', 'Corporate', 'Home Office']
Gender : ['Male', 'Female']
Minimum Age : 18
Maximum Age : 70

In [14]:
customer_ids = [
    f"C{str(i).zfill(5)}"
    for i in range(1, NUMBER_OF_CUSTOMERS + 1)
]
print(customer_ids[:10])

['C00001', 'C00002', 'C00003', 'C00004', 'C00005', 'C00006', 'C00007', 'C00008', 'C00009', 'C00010']

In [15]:
print("Number of Customer IDs Generated:", len(customer_ids))

print("Unique Customer IDs:", len(set(customer_ids)))

Number of Customer IDs Generated: 15000
Unique Customer IDs: 15000

In [16]:
customer_name_list = []

gender_list = []

age_list = []

city_list = []

state_list = []

segment_list = []

In [17]:
for customer in customer_ids:
  customer_name = fake.name()
  gender = np.random.choice(
      genders,
      p=gender_probability
  )

  age = random.randint(
      MIN_AGE,
      MAX_AGE
  )

  city = random.choice(cities)

  state = city_state[city]

  segment = np.random.choice(
      segments,
      p=segment_probability
  )

  customer_name_list.append(customer_name)
  gender_list.append(gender)
  age_list.append(age)
  city_list.append(city)
  state_list.append(state)
  segment_list.append(segment)

In [19]:
customers_df = pd.DataFrame({
    "customer_id":customer_ids,
    "customer_name":customer_name_list,
    "gender":gender_list,
    "age":age_list,
    "city":city_list,
    "state":state_list,
    "segment":segment_list
})

In [21]:
customers_df.head()

,customer_id,customer_name,gender,age,city,state,segment
0,C00001,Aryan Maharaj,Male,58,Pune,Maharashtra,Home Office
1,C00002,Udant Dewan,Female,19,Madurai,Tamil Nadu,Consumer
2,C00003,Gagan Sami,Male,33,Warangal,Telangana,Consumer
3,C00004,Ayushman Chander,Male,26,Mumbai,Maharashtra,Home Office
4,C00005,Viraj Tiwari,Female,61,Thiruvananthapuram,Kerala,Corporate

In [22]:
customers_df.shape

(15000, 7)

In [23]:
customers_df.columns

Index(['customer_id', 'customer_name', 'gender', 'age', 'city', 'state',
       'segment'],
      dtype='object')

In [24]:
customers_df.dtypes

customer_id      object
customer_name    object
gender           object
age               int64
city             object
state            object
segment          object
dtype: object

In [25]:
customers_df.sample(10)

,customer_id,customer_name,gender,age,city,state,segment
7475,C07476,Netra Lala,Female,41,Surat,Gujarat,Consumer
10524,C10525,Mugdha Shenoy,Female,44,Varanasi,Uttar Pradesh,Consumer
8991,C08992,Pushti Varghese,Female,48,Indore,Madhya Pradesh,Consumer
11201,C11202,Jeet Ghose,Female,44,Bhubaneswar,Odisha,Consumer
4847,C04848,Nandini Sahota,Male,59,Gaya,Bihar,Consumer
10876,C10877,Dalaja Thaman,Female,23,Vadodara,Gujarat,Consumer
1463,C01464,Neel Oza,Female,56,Varanasi,Uttar Pradesh,Home Office
4334,C04335,Triveni Sethi,Male,29,Vadodara,Gujarat,Corporate
7790,C07791,Viraj Nigam,Female,45,Delhi,Delhi,Consumer
7892,C07893,Madhav Gour,Female,42,Amritsar,Punjab,Consumer

In [26]:
customers_df["age"].describe()

count    15000.000000
mean        43.830267
std         15.308094
min         18.000000
25%         30.000000
50%         44.000000
75%         57.000000
max         70.000000
Name: age, dtype: float64

In [27]:
customers_df["segment"].value_counts()

segment
Consumer       9001
Corporate      3744
Home Office    2255
Name: count, dtype: int64

In [28]:
customers_df["gender"].value_counts()

gender
Female    7514
Male      7486
Name: count, dtype: int64

In [29]:
customers_df["city"].value_counts().head(15)

city
Nashik                423
Ranchi                421
Patna                 414
Thiruvananthapuram    413
Nagpur                405
Mysuru                395
Ahmedabad             394
Pune                  394
Indore                393
Jodhpur               389
Raipur                387
Bengaluru             386
Jaipur                379
Lucknow               379
Mumbai                378
Name: count, dtype: int64

In [30]:
customers_df["state"].value_counts()

state
Uttar Pradesh       1839
Maharashtra         1600
Karnataka           1144
Tamil Nadu          1090
Gujarat             1072
Bihar                775
Kerala               770
Madhya Pradesh       770
Rajasthan            768
West Bengal          734
Odisha               729
Punjab               723
Telangana            698
Jharkhand            421
Chhattisgarh         387
Uttarakhand          375
Himachal Pradesh     371
Assam                368
Delhi                366
Name: count, dtype: int64

In [31]:
customers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    15000 non-null  object
 1   customer_name  15000 non-null  object
 2   gender         15000 non-null  object
 3   age            15000 non-null  int64
 4   city           15000 non-null  object
 5   state          15000 non-null  object
 6   segment        15000 non-null  object
dtypes: int64(1), object(6)
memory usage: 820.4+ KB

In [32]:
customers_df.isnull().sum()

customer_id      0
customer_name    0
gender           0
age              0
city             0
state            0
segment          0
dtype: int64

In [34]:
customers_df["customer_id"].duplicated().sum()

np.int64(0)

In [35]:
customers_df["age"].min(), customers_df["age"].max()

(18, 70)

In [36]:
customers_df[
    (customers_df["age"] < 18) |
    (customers_df["age"] > 70)
]

Empty DataFrame
Columns: [customer_id, customer_name, gender, age, city, state, segment]
Index: []

In [37]:
customers_df["gender"].unique()

array([np.str_('Male'), np.str_('Female')], dtype=object)

In [38]:
customers_df["segment"].unique()

array([np.str_('Home Office'), np.str_('Consumer'), np.str_('Corporate')],
      dtype=object)

In [39]:
for city, state in zip(customers_df["city"], customers_df["state"]):

    if city_state[city] != state:

        print(city, state)

In [40]:
customers_df["city"].nunique()

40

In [41]:
customers_df["state"].nunique()

19

In [42]:
round(
    customers_df["segment"]
    .value_counts(normalize=True) * 100
    ,2
)

segment
Consumer       60.01
Corporate      24.96
Home Office    15.03
Name: proportion, dtype: float64

In [43]:
round(
    customers_df['gender']
    .value_counts(normalize=True) * 100
    ,2
)

gender
Female    50.09
Male      49.91
Name: proportion, dtype: float64

In [44]:
customers_df.sample(20)

,customer_id,customer_name,gender,age,city,state,segment
5153,C05154,Ikbal Zacharia,Female,32,Kanpur,Uttar Pradesh,Consumer
13014,C13015,Nirja Virk,Male,30,Mysuru,Karnataka,Home Office
7230,C07231,Jhalak Mallick,Female,26,Warangal,Telangana,Corporate
4049,C04050,Victor Joshi,Male,39,Nagpur,Maharashtra,Consumer
1180,C01181,Dhriti Sandhu,Male,42,Shimla,Himachal Pradesh,Consumer
12584,C12585,Tanmayi Krishnan,Female,69,Lucknow,Uttar Pradesh,Consumer
4652,C04653,Joshua Srinivas,Female,33,Bhopal,Madhya Pradesh,Consumer
12090,C12091,Sathvik Patla,Male,25,Lucknow,Uttar Pradesh,Corporate
9052,C09053,Dakshesh Mitter,Male,44,Amritsar,Punjab,Corporate
4103,C04104,Lekha Bava,Male,68,Delhi,Delhi,Consumer
9234,C09235,Patrick Kothari,Male,66,Patna,Bihar,Consumer
3849,C03850,Chameli Banik,Male,24,Thiruvananthapuram,Kerala,Consumer
1825,C01826,Charan Manne,Female,62,Nagpur,Maharashtra,Consumer
11689,C11690,Lohit Walia,Female,37,Nagpur,Maharashtra,Consumer
6329,C06330,Radhika Sahni,Female,62,Jodhpur,Rajasthan,Corporate
1447,C01448,Oviya Tata,Male,48,Chennai,Tamil Nadu,Home Office
8725,C08726,Samar Chana,Female,33,Bhopal,Madhya Pradesh,Consumer
12173,C12174,Omisha Arya,Female,43,Varanasi,Uttar Pradesh,Consumer
1471,C01472,Girish Bhatt,Male,65,Pune,Maharashtra,Corporate
13161,C13162,Vrishti Kumar,Male,24,Indore,Madhya Pradesh,Consumer

In [45]:
customers_df = customers_df.sort_values(
    by='customer_id'
)

In [46]:
customers_df.reset_index(
    drop=True,
    inplace=True
)

In [47]:
customers_df.sample(20)

,customer_id,customer_name,gender,age,city,state,segment
14542,C14543,Waida Merchant,Male,47,Cuttack,Odisha,Consumer
3210,C03211,Arin Chauhan,Female,30,Kochi,Kerala,Consumer
11872,C11873,Ishanvi Mohanty,Male,51,Chandigarh,Punjab,Consumer
14679,C14680,Nikita Chhabra,Female,62,Bhubaneswar,Odisha,Corporate
11605,C11606,Nathaniel Gour,Male,55,Coimbatore,Tamil Nadu,Consumer
10250,C10251,Wyatt Sathe,Male,58,Patna,Bihar,Consumer
8214,C08215,Arjun Nigam,Male,24,Agra,Uttar Pradesh,Consumer
4949,C04950,Brijesh Singh,Female,64,Nagpur,Maharashtra,Consumer
2894,C02895,Zaid Sahota,Female,45,Delhi,Delhi,Consumer
5364,C05365,Neelima Gaba,Male,42,Kanpur,Uttar Pradesh,Corporate
7714,C07715,Kritika Chacko,Female,65,Nagpur,Maharashtra,Consumer
6468,C06469,Ekani Nair,Female,21,Hyderabad,Telangana,Consumer
12045,C12046,Liam Bhavsar,Male,67,Amritsar,Punjab,Consumer
9465,C09466,Madhavi Sarraf,Male,41,Kolkata,West Bengal,Home Office
6336,C06337,Riya Vohra,Female,56,Mysuru,Karnataka,Consumer
13797,C13798,Mugdha Din,Female,24,Kochi,Kerala,Consumer
5458,C05459,Matthew Doshi,Male,51,Surat,Gujarat,Consumer
11485,C11486,Ekaja Prabhu,Female,42,Thiruvananthapuram,Kerala,Corporate
8959,C08960,Rishi Amble,Male,40,Surat,Gujarat,Home Office
14374,C14375,Tejas Sidhu,Male,54,Hyderabad,Telangana,Consumer

In [48]:
import os

os.makedirs('Data/Generated',exist_ok=True)

In [49]:
customers_df.to_csv(
    "Data/Generated/customers.csv",
    index=False
)

In [50]:
from google.colab import files

files.download("Data/Generated/customers.csv")

In [51]:
print("="*50)

print("CUSTOMER DATASET GENERATED SUCCESSFULLY")

print("="*50)

print(f"Total Customers : {len(customers_df)}")

print(f"Unique Customers : {customers_df['customer_id'].nunique()}")

print(f"Missing Values : {customers_df.isnull().sum().sum()}")

print(f"Unique Cities : {customers_df['city'].nunique()}")

print(f"Unique States : {customers_df['state'].nunique()}")

print("="*50)

==================================================
CUSTOMER DATASET GENERATED SUCCESSFULLY
==================================================
Total Customers : 15000
Unique Customers : 15000
Missing Values : 0
Unique Cities : 40
Unique States : 19
==================================================